language: scala

install:
  - wget https://github.com/MiniZinc/libminizinc/releases/download/2.1.5/minizinc-2.1.5-linux64.tar.gz
  - tar xzf minizinc-2.1.5-linux64.tar.gz
  - export PATH=$PATH:$PWD/minizinc-2.1.5/bin

script:
  - make ci-tests
